### PR TITLE
Hickory

### LINKED ISSUE #61: hickory and other jsoup dependents are incompatible
Idk where else to document this in a public manner.
Hickory, as well as most other projects labeling themselves as html parsers don't play nicely with graalvm.
This is because jsoup wants to be initialized at runtime and clojure libs at build time.
The project where I tried for days to get it to play with graal: [bbyt](https://github.com/port19x/bbyt)

### PR DESCRIPTION
**Pull request by port19x**
closes #61 

Opening this one early for visibility and convenience.
Todo:

- [x] add the library to the project.clj and the native-image parameters used
- [x] amend the my-library/src/simple/main.clj to use the library
- [x] amend the my-library/README.md with the info you discovered.

### CODE REVIEW

**Comment by port19x** [comment]
Note `native-image` is not a command under a normal archlinux installation of graalvm.
You need to specify the full qualified path.
I modified the project-clj to reflect that.

**Comment by port19x** [comment]
I'd reasonably expect anyone who wants to use hickory to use some requests library too.
Would it be reasonable to extend my demo to cover that?

**Comment by port19x** [comment]
First observation: `org.clj-commons/hickory` doesn't compile with graalvm, while `hickory/hickory` does.
This might indicate some regression on 0.7.2+ that I might investigate via a git bisect.

**Comment by port19x** [comment]
Converting to draft again as I'm now maintainer of hickory and working on ironing out the incompatibility in clj-commons/hickory#77

**Comment by port19x** [comment]
I consider this done

**Comment by port19x** [comment]
@BrunoBonacci

**Comment by BrunoBonacci** [comment]
thank you

**Pull request merged**
